# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring:
  ai:
    mcp:
      server:
        name: openapi-collector-server
        version: 0.0.1
#        stdio: true
        enabled: true
        type: async

logging:
  file:
    name: /Users/a80128103/workspace/ollama/spring-ai-examples/model-context-protocol/weather/starter-webflux-server/target/starter-stdio-server.log
