# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
spring:
  ai:
    mcp:
      server:
        name: openapi-collector-server
        version: 0.0.1
#        stdio: true
        enabled: true
        type: sync

logging:
  file:
    name: ./target/server.log
