name: PR Build and Lint

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run lint checks
        run: ./gradlew checkstyleMain checkstyleTest

      - name: Build and test
        run: ./gradlew build

      - name: Upload Checkstyle reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/
          if-no-files-found: ignore